# Generated by Django 3.2.5 on 2021-07-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armaan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
